version: '3.1'
services:
  portal:
    image: 848839979695.dkr.ecr.ap-southeast-1.amazonaws.com/portal:latest
    depends_on:
      - psql
    ports:
      - "8069:8069"
    volumes:
      - data:/var/lib/odoo
      - filestore:/root/.local/share/Odoo/filestore
      - ./config:/etc/odoo
  psql:
    image: postgres:13
    env_file: .env
    volumes:
      - db:/var/lib/pgsql/data/pgdata
    ports:
      - "5432:5432"
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/:/etc/nginx
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - portal
volumes:
  data:
  db:
  filestore:
